export const categories = {
  'Alligators and crocodiles': '🐊',
  Ants: '🐜',
  Arachnids: '🕸️',
  Bats: '🦇',
  Bears: '🐻',
  Birds: '🐦',
  Canines: '🐕',
  Cockroaches: '🪳',
  Crustaceans: '🦀',
  Felines: '🐈',
  Fish: '🐟',
  Gastropods: '🐌',
  'Honey bees': '🐝',
  Locusts: '🦗',
  Octopus: '🐙',
  Pigs: '🐖',
  Piranhas: '🐟',
  Plants: '🌱',
  Primate: '🐒',
  Rabbits: '🐇',
  Rats: '🐀',
  Sharks: '🦈',
  Sheep: '🐑',
  Snakes: '🐍',
  Wasps: '🐝',
  Worms: '🐛',
};
